### ISSUE TITLE
License file not present in systemd crate

### ISSUE THREAD

**Issue by remilauzier** [jmesmon/rust-systemd#186]
Hi!
Would like to know if you could include the license file in the cargo crate to satisfy fedora packaging.

**Comment by jmesmon** [comment]
Hi, I'm interested in this issue and making it straightforward to package this crate on various distros.

It does seem a bit abnormal to include the license file itself in the `.crate` file because there's already machine readable metadata in the crate to indicate the licensing (and if there's a custom license, that file gets included).

Can you link me to the fedora packaging standards/policies that require/seem to require this? Also, some links to already packaged crates could be helpful in understanding all the needs here.

**Comment by remilauzier** [comment]
Here are the rust packaging guideline for fedora. https://docs.fedoraproject.org/en-US/packaging-guidelines/Rust/
Here are the link to the licensing requirement for fedora. https://docs.fedoraproject.org/en-US/packaging-guidelines/LicensingGuidelines/#_license_text
Here are a link to `ripgrep`. https://src.fedoraproject.org/rpms/rust-ripgrep/blob/rawhide/f/rust-ripgrep.spec
Hope that will help you and thanks for answering my bugs reports.
Fedora prefer to be strict with there package guideline. Should just be a matter of putting the license file in `include` in `cargo.toml`

**Comment by remilauzier** [comment]
For `readme.md` fedora calculate that as documentation. https://docs.fedoraproject.org/en-US/packaging-guidelines/#_documentation
