### ISSUE TITLE
Escaping unit names

### ISSUE THREAD

**Issue by lunaryorn** [jmesmon/rust-systemd#197]
I had to implement escaping of unit names for one of my projects, and wondered if it would be a suitable addition to this crate.  It's as simple as the code below; I'm happy to open a pull request if it's acceptable.

```rust
/// Escape a string for use in a systemd unit name.
///
/// See <https://www.freedesktop.org/software/systemd/man/systemd.unit.html#String%20Escaping%20for%20Inclusion%20in%20Unit%20Names>
fn systemd_escape(s: &str) -> String {
    let mut escaped = String::with_capacity(s.len());
    for b in s.bytes() {
        match b {
            b'/' => escaped.push('-'),
            // _ and : are not escaped, and '.' only at the beginning (see below).
            b'.' | b'_' | b':' => escaped.push(b as char),
            // ASCII alpha numberic chars are not escaped
            _ if b.is_ascii_alphanumeric() => escaped.push(b as char),
            _ => escaped.push_str(&format!("\\x{:02x}", b)),
        }
    }
    // systemd requires a leading dot (and only a leading dot) to be escaped.
    if escaped.starts_with('.') {
        escaped.replacen('.', "\\x2e", 1)
    } else {
        escaped
    }
}
```

**Comment by jmesmon** [comment]
Sure, something to escape unit names could definitely be included and I'd be happy to merge it.

I did take a look at the libsystemd crate (https://lib.rs/crates/libsystemd, a pure rust implementation of a subset of the functionality in the systemd dynamic library this `systemd` crate exposes), and it looks like there is an implementation of escaping unit names in that crate: https://docs.rs/libsystemd/0.2.1/libsystemd/unit/fn.escape_name.html .

I guess we have an alternate here which is having folks use `libsystemd` when they need this functionality. That said, I'm fine with either option here. If there's a PR for this, I'll merge it because it makes sense.

Thoughts?

**Comment by lunaryorn** [comment]
I don't know.  I didn't know about libsystemd; had I known it I likely would have used it in the first place :slightly_smiling_face:
