### ISSUE TITLE
Couldn't read from newly created .journal files in /var/log/journal/xxxxxxx/ dynamically

### ISSUE THREAD

**Issue by tekjar** [jmesmon/rust-systemd#22]
When writing continuously to journal, new `.journal` files gets created in `/var/log/journal/$RANDOM_NAME`/ dynamically. journal `next_record` is returning `Ok(None)` in the case where next journal writes are going to newly created `.journal` file.

``` rust
extern crate systemd;
use systemd::journal::{Journal, JournalFiles, JournalRecord, JournalSeek};
use std::thread;
use std::time::Duration;

fn main() {
    let mut journal = Journal::open(JournalFiles::All, false, false)
        .expect("Failed to open journal");
    let count: u64 = 0;
    loop {
        let record = match journal.next_record().unwrap() {
            Some(record) => {
                count += 1;
                println!("{:?}", count);
            }
            None => {
                println!("Done .........");
                thread::sleep(Duration::new(3, 0));
            }
        };
    }

}
```

I'm not sure if I'm doing something wrong here

**Comment by lucab** [comment]
Which systemd/journald version is running and on which OS? What is the rotation policy in `journald.conf`? I guess you are you writing to the system journal, are you hitting some -ENOSPC or other limit conditions? Can you try to reproduce it without filling the journal, but just by performing a manual journal rotation via `journalctl --rotate`?

**Comment by kteza1** [comment]
Hi @lucab 

> Which systemd/journald version is running and on which OS?

I'm on Ubuntu 15.10 with systemd 225 (journalctl --rotate isn't available here to test :( )

Here is my config (to make sure that I don't loose any records because of the rate at which I'm writing)

```
[Journal]
RateLimitInterval=5
RateLimitBurst=5000000
```

A simple test case for this would be

* sudo rm -rf /var/log/journal/bec98340ef464090b1528e671942a971/
* sudo systemctl restart systemd-journald
* run the above code (you'll see `Done ....` after few secs)
* write to journal (`user-nnn.journal` gets created in `/var/log/journal/xxxxxx/`)
* but you still see `Done ...` being printed instead of reading new records

This might be because `sd_journal_next` is not tracking new file descriptors after log rotation. [I've added binding for `sd_journal_wait`] (https://github.com/kteza1/rust-systemd/blob/master/src/journal.rs#L181-L184)  and things seem to work with below code

```rust
loop {
        let record = match journal.next_record().unwrap() {
            Some(record) => {
                count += 1;
                println!("{:?}", count);
            }
            None => {
                println!("Done .........");
                journal.wait(10);
                thread::sleep(Duration::new(3, 0));
            }
        };
 }
```

**Comment by ibotty** [comment]
@tekjar, would you care to submit a pull request for the `Journal::wait`. I also need that one. Hope @jmesmon agrees.

**Comment by jmesmon** [comment]
I've (very belatedly) exposed the api for `wait` publicly in #124 .
