### ISSUE TITLE
start/stop service example

### ISSUE THREAD

**Issue by bernardoaraujor** [jmesmon/rust-systemd#242]
I have a `.service` file under `/lib/systemd/system/`, which I want to use to orchestrate a systemd service from my rust app.

I'm kind of a `DBus` n00b, so I'm having trouble finding my way to get this to work.

a simple implementation of a `examples/start_service.rs` would be really helpful 🙏

**Comment by jmesmon** [comment]
Hi @bernardoaraujor, thanks for your interest in the `rust-systemd` crate. 

For the high-level how to, systemd's API for starting/stopping services is documented [here on freedesktop.org](https://www.freedesktop.org/wiki/Software/systemd/dbus/). The method you'll want to use for starting the service is `StartUnit`.

Assuming your service is named `foo` (and has a `foo.service` unit installed), using command line tools one could start it with this command:

```
busctl --system call  org.freedesktop.systemd1 /org/freedesktop/systemd1 org.freedesktop.systemd1.Manager StartUnit "ss" "foo.service" "fail"
```
(note that you'll  need permissions to do this. being `root` is usually enough, otherwise one can use polkit to manage what types of dbus calls are allowed).

Back to this crate.

What you'd need to do if using `rust-systemd` for starting a service like this is write something that uses the `systemd::bus` module, which exposes the `sd-bus` dbus library from systemd. There aren't any helpers for performing dbus interactions with systemd itself (like we need to do here to start a service).

To be completely honest here: the `systemd::bus` module (the rust code here) is not very well tested. You might have better luck using another rust dbus library to do this. I've used [zbus](https://docs.rs/zbus/latest/zbus/) in the past and found it OK-ish (and it's pure rust, unlike `rust-systemd` which is linking to `libsystemd`).

Anyhow, here's how one might use `systemd::bus` to perform this call:

```
use utf8_cstr::Utf8CStr;
fn main() {
    let mut bus = systemd::bus::Bus::default_system().unwrap();

    let mut method_call = bus
        .new_method_call(
            systemd::bus::BusName::from_bytes(b"org.freedesktop.systemd1\0").unwrap(),
            systemd::bus::ObjectPath::from_bytes(b"/org/freedesktop/systemd1\0").unwrap(),
            systemd::bus::InterfaceName::from_bytes(b"org.freedesktop.systemd1.Manager\0").unwrap(),
            systemd::bus::MemberName::from_bytes(b"StartUnit\0").unwrap(),
        )
        .unwrap();

    // args
    method_call
        .append(Utf8CStr::from_bytes(b"foo.service\0").unwrap())
        .unwrap();
    method_call
        .append(Utf8CStr::from_bytes(b"fail\0").unwrap())
        .unwrap();

    let res = method_call.call(0).unwrap();

    // eprintln!("done, result={:?}", *res);
}
```

Note that this works, but there's some issues with printing the method call result which currently hit asserts (which is why that line is commented).

Alternately, here's how one would use zbus:

```
fn main() -> Result<(), zbus::Error> {
    let connection = zbus::Connection::new_system()?;

    let res = connection.call_method(
        Some("org.freedesktop.systemd1"),
        "/org/freedesktop/systemd1",
        Some("org.freedesktop.systemd1.Manager"),
        "StartUnit",
        &("foo.service", "fail"),
    )?;

    dbg!(res);
    Ok(())
}
```
(zbus also has some macro-magic way of defining proxy objects that can be useful too, but I have not used it here).
