### ISSUE TITLE
journal: when seeking to head or tail, impossible to get first (or last) log entry

### ISSUE THREAD

**Issue by ibotty** [jmesmon/rust-systemd#31]
That's because `seek` calls `sd_journal_next` and when iterating over entries (`while let Some(entry) = journal.next_record()? {...}`), it will get the second entry.

Is there any reason to get next entry when seeking? AFAICT there is no public api to get the current data.

**Comment by jmesmon** [comment]
Ya, that does look broken.

To clarify the issue here:

 - `Journal::seek()` currently returns a journal cursor.
 - getting a journal cursor is done via `sd_journal_get_cursor()`, which notes that `sd_journal_get_cursor() will not work before sd_journal_next(3) (or related call) has been called
       at least once, in order to position the read pointer at a valid entry`
 - to handle that `Journal::seek()` currently calls `sd_journal_next()` if the call to `sd_journal_get_cursor` fails.

Solutions here:

 1. don't return a journal cursor from `Journal::seek()` and don't call sd_journal_next()` in `Journal::seek()`. This means that `Journal::cursor()` will fail in some cases as we aren't always positioned on a valid journal entry.

2. Use `sd_journal_previous()` + `sd_journal_next()` to align ourselves properly without skipping any journal entries. This allows keeping current behavior, but means `seek` is more expensive.

It seems like option 1, which is closer to systemd's actual API may be the better choice here.

**Comment by ibotty** [comment]
I think 3 won't work, because `Journal::cursor` won't be correct. I Agree that option 1 looks most reasonable. In `Journal::cursor` I would prefer to just return an error in case `sd_journal_get_cursor` fails, not wrap it in an `Option`.

**Comment by lucab** [comment]
I don't completely agree:
 * `Journal::get_record` already exists for retrieving current entry
 * `Journal::seek` is an higher level operation compared to `sd_journal_seek_*`: re-aligning to a real entry entry is there to make head/tail seeks less surprising, and the cursor is returned there to make the test_cursor dance easier (similarly to `std::io::Seek` trait). Moving out this logic from there means that it will need to be duplicated at every calling site.

I think the main problem here is that @ibotty is trying to use `next_record()` with the same semantics as `next()` from `Iterator` trait, which in reality it is not. If we want to do that, we should properly implement that trait (or `Rev` perhaps) instead of hammering existing API, but please do note that iterators are not seekable (I think exactly for the reasons we are discussing here).

**Comment by ibotty** [comment]
`Journal::get_record` is not public, so cannot be used. You could, of course, make it public.

I don't get your reasoning re `Journal::seek`. AFAICT there is no public API (except `cursor` and `timestamp`) that does not already use `sd_journal_next` or `sd_journal_previous`.

And btw: you are right. I do try to iterate using `next_record`. I don't know how one would implement a safe Iterator though. Being able to seek destroys that.

**Comment by ibotty** [comment]
What's your plan on fixing that? I might help implementing it.

**Comment by jlebon** [comment]
> `Journal::seek` is an higher level operation compared to `sd_journal_seek_*`: re-aligning to a real entry entry is there to make head/tail seeks less surprising

One thing that bit me hard recently actually was that *because* `Journal::seek()` uses `sd_journal_next` automatically, one has to remember to `match_flush()` before calling it or the cursor might not be where you want it. E.g. I had:

```rust
    j.seek(journal::JournalSeek::Cursor {
        cursor: my_cursor,
    })?;
```

But that didn't actually place it at the cursor specified in `my_cursor` because the `sd_journal_next()` call then moved it to whatever next record matched the current match rules.

Anyway, might just be a doc fix, though overall I do prefer solution 1 (or at least split it out the pure seeking part into its own API for finer grained control; e.g. you may sometimes want `sd_journal_previous()` instead of `sd_journal_next()` from a given cursor/timestamp you seeked to).

**Comment by jmesmon** [comment]
FWIW: I went with option `1` from my earlier comment here. The interface this is providing is (for now) going to more closely mirror the C api so that everyone can get the functionality they need out of it.

There may be some use for good abstrations over that, but we didn't have the right ones initially.
