### ISSUE TITLE
A journal reading API that doesn't allocate?

### ISSUE THREAD

**Issue by lilydjwg** [jmesmon/rust-systemd#91]
The `Journal::next_record` API allocates a lot of `String`s and one `BTreemap` for each record. This isn't efficient if it's not actually needed.

I'm reading all journal records to collect some statistical data. I've implemented a simple function to access the raw data and my program running time has reduced from ~11s to 4.7s:

```rust
    pub fn next_record_raw<F>(&mut self, mut func: F) -> Result<Option<()>>
      where F: FnMut(&[u8])
    {
        if sd_try!(ffi::sd_journal_next(self.j)) == 0 {
            return Ok(None);
        }

        let mut sz: size_t = 0;
        let data: *mut u8 = ptr::null_mut();
        while sd_try!(ffi::sd_journal_enumerate_data(self.j, &data, &mut sz)) > 0 {
            let b = unsafe {
                ::std::slice::from_raw_parts_mut(data, sz as usize)
            };
            func(b);
        }

        Ok(Some(()))
    }
```

What do you think?

**Comment by jmesmon** [comment]
I definitely think optimizations on journal record reading would be good to have. I'm not sure about the use of internal iteration though: most rust apis try to avoid internal iteration (ie: callbacks) in favor of external iteration (ie: for loops).

Is there some way to formulate it efficiently as external iteration? Perhaps by providing some iteration-like API around this (I don't think it could quite be an iterator due to the need to constrain other accesses to the journal handle while using `sd_journal_enumerate_data()`, but I might be wrong).
