### ISSUE TITLE
Why use LGPL?

### ISSUE THREAD

**Issue by janderholm** [jmesmon/rust-systemd#92]
Currently this crate uses LGPL-2.1+ as license. If I understand things correctly this means anyone who links with it statically (i.e. everyone in rust projects) will be required to use LGPL or GPL on their work as well.

Looking at crates.io this doesn't seem to be honored at all, but that's their problem. I wonder why use LGPL instead of MIT which seems like the standard license?

I suspect it is because the C systemd library uses LGPL. But since the crate links with the C library dynamically, the crate does not need to use LGPL.

**Comment by jmesmon** [comment]
Yes, it only uses `LGPL` because the underlying libsystemd library uses `LGPL`. I'm open to adjusting it.

**Comment by bestouff** [comment]
> Currently this crate uses LGPL-2.1+ as license. If I understand things correctly this means anyone who links with it statically (i.e. everyone in rust projects) will be required to use LGPL or GPL on their work as well

IANAL but I think you're mistaken. The "spirit" of the LGPL is that any program can use the library without being itself (L)GPL - otherwise any program using the `glibc` (i.e. virtually everything on Linux) would have to be relicensed to (L)GPL. Static or dynamic linking has nothing to do with it (it's a common urban myth).  
On the other hand, if your binary is proprietary you would have to provide some kind of object file to allow people to "relink" to a different version of the LGPL lib, which is doable but not trivial with Rust.

**Comment by skrap** [comment]
> Static or dynamic linking has nothing to do with it (it's a common urban myth).

https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic

Static or dynamic linking does seem to be a critical distinction, if you believe gnu.org.  All of the proprietary programs on linux dynamically linking against glibc avoid falling under the LGPL because of exactly this fact.  The fact that this crate is LGPL rather than BSD (or similar) keeps me from using it in my proprietary program, because the spirit of the LGPL could not be upheld.  And to be clear: I don't fault the author - if that's the intention, I completely support it, as people should be able to write under whatever license they want!

However, if the intention is that Rust programs (which would statically link against this crate due to the nature of Rust) should be able to use the crate while remaining proprietary, then the license would need to be changed.
